In [52]:
import pandas as pd

labels_path = "data/train_labels.csv"
sequences_path = "data/train_sequences.csv"

labels = pd.read_csv(labels_path).dropna()
sequences = pd.read_csv(sequences_path)
sequences.head()

,target_id,sequence,temporal_cutoff,description,all_sequences
0,1SCL_A,GGGUGCUCAGUACGAGAGGAACCGCACCC,1995-01-26,"THE SARCIN-RICIN LOOP, A MODULAR RNA",>1SCL_1|Chain A|RNA SARCIN-RICIN LOOP|Rattus n...
1,1RNK_A,GGCGCAGUGGGCUAGCGCCACUCAAAAGGCCCAU,1995-02-27,THE STRUCTURE OF AN RNA PSEUDOKNOT THAT CAUSES...,>1RNK_1|Chain A|RNA PSEUDOKNOT|null\nGGCGCAGUG...
2,1RHT_A,GGGACUGACGAUCACGCAGUCUAU,1995-06-03,24-MER RNA HAIRPIN COAT PROTEIN BINDING SITE F...,>1RHT_1|Chain A|RNA (5'-R(P*GP*GP*GP*AP*CP*UP*...
3,1HLX_A,GGGAUAACUUCGGUUGUCCC,1995-09-15,P1 HELIX NUCLEIC ACIDS (DNA/RNA) RIBONUCLEIC ACID,>1HLX_1|Chain A|RNA (5'-R(*GP*GP*GP*AP*UP*AP*A...
4,1HMH_E,GGCGACCCUGAUGAGGCCGAAAGGCCGAAACCGU,1995-12-07,THREE-DIMENSIONAL STRUCTURE OF A HAMMERHEAD RI...,">1HMH_1|Chains A, C, E|HAMMERHEAD RIBOZYME-RNA..."

In [53]:
labels.head()

         ID resname  resid     x_1        y_1     z_1
0  1SCL_A_1       G      1  13.760 -25.974001   0.102
1  1SCL_A_2       G      2   9.310 -29.638000   2.669
2  1SCL_A_3       G      3   5.529 -27.813000   5.878
3  1SCL_A_4       U      4   2.678 -24.900999   9.793
4  1SCL_A_5       G      5   1.827 -20.136000  11.793

In [54]:
# ------- Examining the DataFrame Studying Pair Distances -------
import pandas as pd
import numpy as np

# Assuming your DataFrame 'labels' is already loaded
# Use only the first 20 residues for the example
coords = labels[['x_1', 'y_1', 'z_1']][100:110].values

# Calculate the pairwise Euclidean distance matrix.
diff = coords[:, None, :] - coords[None, :, :]
dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))

# For each of the first 20 residues, find the closest residue (excluding self)
for i in range(len(coords)):
    distances = dist_matrix[i].copy()
    distances[i] = np.inf  # ignore self-distance
    closest_idx = np.argmin(distances)
    closest_distance = distances[closest_idx]
    
    # Get residue types from the DataFrame
    res_i_type = labels.iloc[i]['resname']
    res_j_type = labels.iloc[closest_idx]['resname']
    
    print(f"Residue {i} ({res_i_type}) is closest to residue {closest_idx} ({res_j_type}) with distance = {closest_distance:.3f} Å")

Residue 0 (G) is closest to residue 1 (G) with distance = 5.526 Å
Residue 1 (G) is closest to residue 0 (G) with distance = 5.526 Å
Residue 2 (G) is closest to residue 3 (U) with distance = 5.069 Å
Residue 3 (U) is closest to residue 2 (G) with distance = 5.069 Å
Residue 4 (G) is closest to residue 5 (C) with distance = 4.956 Å
Residue 5 (C) is closest to residue 4 (G) with distance = 4.956 Å
Residue 6 (U) is closest to residue 5 (C) with distance = 5.500 Å
Residue 7 (C) is closest to residue 8 (A) with distance = 5.594 Å
Residue 8 (A) is closest to residue 9 (G) with distance = 5.394 Å
Residue 9 (G) is closest to residue 8 (A) with distance = 5.394 Å

In [ ]:
import pandas as pd
import numpy as np

IGNORE_BASE_PAIRS = True

IDs = sequences['target_id'].values
pair_stats = {}

for ID in IDs:
    print(f"Processing ID: {ID}")
    # Filter by ID included in string in ID col and x_1 , y_1, z_1 from labels
    coords = labels[labels['ID'].str.contains(ID)]
    coords = coords[:50]

    # Create Distance Matrix Numpy Array
    coords = coords[['x_1', 'y_1', 'z_1']].values
    # Calculate the pairwise Euclidean distance matrix.
    diff = coords[:, None, :] - coords[None, :, :]
    dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))
    # For each of the first 20 residues, find the closest residue (excluding self)


    for i in range(len(coords)):
        distances = dist_matrix[i].copy()
        distances[i] = np.inf  # ignore self-distance
        
        if IGNORE_BASE_PAIRS:
            if i > 2 and i < len(coords) - 3:
                distances[i-3] = np.inf  # ignore base pairs
                distances[i-2] = np.inf  
                distances[i-1] = np.inf
                distances[i+1] = np.inf
                distances[i+2] = np.inf
                distances[i+3] = np.inf
        
        closest_idx = np.argmin(distances)
        closest_distance = distances[closest_idx]
        
        # Get residue types from the DataFrame
        res_i_type = labels.iloc[i]['resname']
        res_j_type = labels.iloc[closest_idx]['resname']
        
        # type is not A C G or U replace with '-'
        if res_i_type not in ['A', 'C', 'G', 'U']:
            res_i_type = 'N'
        if res_j_type not in ['A', 'C', 'G', 'U']:
            res_j_type = 'N'
        
        pair_key = sorted([res_i_type, res_j_type])
        pair_key = tuple(pair_key)
        
        if (res_i_type, res_j_type)in pair_stats:
            if closest_distance > 9:
                # Ignore distances greater than 10
                continue
            
            pair_stats[pair_key]["count"] += 1
            pair_stats[pair_key]["total_distance"] += closest_distance
            pair_stats[pair_key]["min_distance"] = min(pair_stats[pair_key]["min_distance"], closest_distance)
            pair_stats[pair_key]["max_distance"] = max(pair_stats[pair_key]["max_distance"], closest_distance)
            pair_stats[pair_key]["avg_distance"] = pair_stats[pair_key]["total_distance"] / pair_stats[pair_key]["count"]
        else:
            pair_stats[pair_key] = {
                "count": 1,
                "total_distance": closest_distance,
                "min_distance": closest_distance,
                "max_distance": closest_distance,
                "avg_distance": closest_distance,
                "ignore_base_pairs": IGNORE_BASE_PAIRS
            }

# Convert to DataFrame
# turn keys into 1 string each
pair_stats = {f"{k[0]}-{k[1]}": v for k, v in pair_stats.items()}
pair_stats_df = pd.DataFrame.from_dict(pair_stats, orient='index')
# drop total_distance
pair_stats_df = pair_stats_df.drop(columns=["total_distance"])

pair_stats_df

Processing ID: 1SCL_A
Processing ID: 1RNK_A
Processing ID: 1RHT_A
Processing ID: 1HLX_A
Processing ID: 1HMH_E
Processing ID: 1RNG_A
Processing ID: 1MME_D
Processing ID: 1KAJ_A
Processing ID: 1SLO_A
Processing ID: 1BIV_A
Processing ID: 1ANR_A
Processing ID: 1ZIG_A
Processing ID: 1ZIH_A
Processing ID: 1ETF_A
Processing ID: 1ZIF_A
Processing ID: 1KPD_A
Processing ID: 1IKD_A
Processing ID: 1ZDI_S
Processing ID: 1AFX_A
Processing ID: 1EBQ_A
Processing ID: 1EBR_A
Processing ID: 1ULL_A
Processing ID: 1KIS_B
Processing ID: 1KIS_A
Processing ID: 1ATO_A
Processing ID: 1TLR_A
Processing ID: 1VOP_A
Processing ID: 1AQO_A
Processing ID: 1ATV_A
Processing ID: 1ATW_A
Processing ID: 1UUU_A
Processing ID: 1AUD_B
Processing ID: 2U2A_A
Processing ID: 1A4T_A
Processing ID: 1A60_A
Processing ID: 1A51_A
Processing ID: 2A9L_A
Processing ID: 1A1T_B
Processing ID: 1A9N_Q
Processing ID: 3PHP_A
Processing ID: 2TPK_A
Processing ID: 7MSF_S
Processing ID: 5MSF_S
Processing ID: 1LDZ_A
Processing ID: 1ZDK_S
Processing ID: 1BVJ_A
Processing ID: 1B36_A
Processing ID: 1HVU_I
Processing ID: 1BGZ_A
Processing ID: 2BJ2_B
Processing ID: 2BJ2_A
Processing ID: 28SP_A
Processing ID: 1QFQ_A
Processing ID: 17RA_A
Processing ID: 1BAU_B
Processing ID: 1BZ2_A
Processing ID: 1CQ5_A
Processing ID: 1QC8_A
Processing ID: 484D_B
Processing ID: 1D6K_B
Processing ID: 1EIY_C
Processing ID: 1ESH_A
Processing ID: 1EXY_A
Processing ID: 1D0U_A
Processing ID: 1ESY_A
Processing ID: 1EUQ_B
Processing ID: 1F9L_A
Processing ID: 1FFK_9
Processing ID: 1EKZ_B
Processing ID: 1F5U_B
Processing ID: 1F6Z_A
Processing ID: 1F6X_A
Processing ID: 1F85_A
Processing ID: 1F84_A
Processing ID: 1FOQ_A
Processing ID: 1FJE_A
Processing ID: 1E4P_A
Processing ID: 1FQZ_A
Processing ID: 1G70_A
Processing ID: 1E7K_D
Processing ID: 1FYO_A
Processing ID: 1FHK_A
Processing ID: 1I3X_A
Processing ID: 1I4C_A
Processing ID: 1I46_A
Processing ID: 1IBM_Y
Processing ID: 1HWQ_A
Processing ID: 1IK1_A
Processing ID: 1E95_A
Processing ID: 1HS2_A
Processing ID: 1JO7_A
Processing ID: 1IDV_A
Processing ID: 1K5I_A
Processing ID: 1K9W_A
Processing ID: 1JTW_A
Processing ID: 1K6G_A
Processing ID: 1K4B_A
Processing ID: 1K4A_A
Processing ID: 1K6H_A
Processing ID: 1JUR_A
Processing ID: 1KKS_A
Processing ID: 1JWC_A
Processing ID: 1L1C_C
Processing ID: 1KP7_A
Processing ID: 1JOX_A
Processing ID: 1K2G_A
Processing ID: 1L1W_A
Processing ID: 1LC6_A
Processing ID: 1LS2_B
Processing ID: 1KKA_A
Processing ID: 1MFY_A
Processing ID: 1M5L_A
Processing ID: 1MFJ_A
Processing ID: 1MFK_A
Processing ID: 1N34_A
Processing ID: 1JTJ_A
Processing ID: 1MT4_A
Processing ID: 1MNX_A
Processing ID: 1NA2_A
Processing ID: 1NC0_A
Processing ID: 1N8X_A
Processing ID: 1OQ0_A
Processing ID: 1OW9_A
Processing ID: 1OSW_A
Processing ID: 1M82_A
Processing ID: 1NYB_B
Processing ID: 1PJY_A
Processing ID: 1P6V_B
Processing ID: 1P6V_D
Processing ID: 1N66_A
Processing ID: 1HS1_A
Processing ID: 1HS8_A
Processing ID: 1HS4_A
Processing ID: 1HS3_A
Processing ID: 1JZC_A
Processing ID: 1QZC_C
Processing ID: 1P5M_A
Processing ID: 1R2W_C
Processing ID: 1P5N_A
Processing ID: 1QZC_B
Processing ID: 1P5P_A
Processing ID: 1QZA_B
Processing ID: 1QZB_B
Processing ID: 1QWB_A
Processing ID: 1QWA_A
Processing ID: 1Q75_A
Processing ID: 1R2P_A
Processing ID: 1RFR_A
Processing ID: 1S9S_A
Processing ID: 1RY1_E
Processing ID: 1SZY_A
Processing ID: 1ROQ_A
Processing ID: 1R7W_A
Processing ID: 1R7Z_A
Processing ID: 1T4L_A
Processing ID: 1WKS_A
Processing ID: 1T28_A
Processing ID: 1S34_A
Processing ID: 1TJZ_A
Processing ID: 1TXS_A
Processing ID: 1R4H_A
Processing ID: 1XHP_A
Processing ID: 1XSG_A
Processing ID: 1Y1Y_P
Processing ID: 1XSH_A
Processing ID: 1YLG_A
Processing ID: 1YNE_A
Processing ID: 1XWU_A
Processing ID: 1XWP_A
Processing ID: 1TBK_A
Processing ID: 1YMO_A
Processing ID: 1Z31_A
Processing ID: 1U63_D
Processing ID: 1ZC8_Z
Processing ID: 1ZC8_G
Processing ID: 1ZC8_J
Processing ID: 1ZC8_F
Processing ID: 1ZC8_I
Processing ID: 1ZC8_H
Processing ID: 1Z30_A
Processing ID: 1X18_D
Processing ID: 1X18_A
Processing ID: 1X18_B
Processing ID: 1ZC5_A
Processing ID: 1ZN1_B
Processing ID: 1Z2J_A
Processing ID: 1YSH_B
Processing ID: 1YSH_A
Processing ID: 1YSH_F
Processing ID: 1YSV_A
Processing ID: 2ADT_A
Processing ID: 1WZ2_D
Processing ID: 2A64_A
Processing ID: 2D19_A
Processing ID: 2D1B_B
Processing ID: 2EUY_A
Processing ID: 2B6G_B
Processing ID: 2ESE_B
Processing ID: 2F4X_B
Processing ID: 2F88_A
Processing ID: 2BQ5_S
Processing ID: 2BS0_R
Processing ID: 2BQ5_R
Processing ID: 2BS0_S
Processing ID: 2G1W_A
Processing ID: 2B2E_R
Processing ID: 2B2E_S
Processing ID: 2GO5_9
Processing ID: 2GO5_A
Processing ID: 2GIP_A
Processing ID: 2GIO_A
Processing ID: 2FEY_A
Processing ID: 2AKE_B
Processing ID: 2DR2_B
Processing ID: 2AGN_C
Processing ID: 2AGN_A
Processing ID: 2IZN_S
Processing ID: 2IZ8_R
Processing ID: 2IZ8_S
Processing ID: 2HGH_B
Processing ID: 2F87_A
Processing ID: 2GV3_A
Processing ID: 2DER_D
Processing ID: 2DET_C
Processing ID: 2EVY_A
Processing ID: 2IXY_A
Processing ID: 2IXZ_A
Processing ID: 2HEM_A
Processing ID: 1ZBH_E
Processing ID: 2AHT_A
Processing ID: 2HNS_A
Processing ID: 2IY3_B
Processing ID: 2J28_8
Processing ID: 2J37_A
Processing ID: 2J28_A
Processing ID: 2NOQ_B
Processing ID: 2NOQ_E
Processing ID: 2NOQ_A
Processing ID: 2FDT_A
Processing ID: 2IHX_B
Processing ID: 2OB7_D
Processing ID: 2FY1_B
Processing ID: 2O33_A
Processing ID: 2IL9_M
Processing ID: 2IL9_A
Processing ID: 2GRW_A
Processing ID: 2DU5_D
Processing ID: 2DU4_C
Processing ID: 2DU6_D
Processing ID: 2GV4_A
Processing ID: 2HUA_A
Processing ID: 2GVO_A
Processing ID: 2PCW_A
Processing ID: 2NR0_H
Processing ID: 2NR0_G
Processing ID: 2NR0_F
Processing ID: 2NR0_E
Processing ID: 2OJ8_A
Processing ID: 2IZM_S
Processing ID: 2JR4_A
Processing ID: 2JPP_C
Processing ID: 2QH3_A
Processing ID: 2QH4_A
Processing ID: 2QH2_A
Processing ID: 2JTP_A
Processing ID: 2OM3_R
Processing ID: 2PN9_A
Processing ID: 2JSE_A
Processing ID: 2R93_R
Processing ID: 2JWV_A
Processing ID: 2OM7_F
Processing ID: 2OM7_J
Processing ID: 2OM7_C
Processing ID: 2OM7_I
Processing ID: 2OM7_G
Processing ID: 2OM7_A
Processing ID: 2OM7_H
Processing ID: 2RLU_A
Processing ID: 2R1G_C
Processing ID: 2R1G_A
Processing ID: 2R1G_X
Processing ID: 2R1G_F
Processing ID: 2R1G_B
Processing ID: 2R1G_E
Processing ID: 2JYM_A
Processing ID: 2JXV_A
Processing ID: 2ZJQ_Y
Processing ID: 2ZJQ_X
Processing ID: 3DEG_I
Processing ID: 3DEG_G
Processing ID: 3DKN_E
Processing ID: 3DEG_J
Processing ID: 3DKN_F
Processing ID: 3DEG_E
Processing ID: 3DKN_D
Processing ID: 3DEG_K
Processing ID: 2RN1_B
Processing ID: 2K95_A
Processing ID: 2K4C_A
Processing ID: 2W2H_S
Processing ID: 3EQ3_E
Processing ID: 3EQ3_Y
Processing ID: 3EP2_B
Processing ID: 3EP2_D
Processing ID: 3EQ4_A
Processing ID: 3EP2_C
Processing ID: 2RPK_A
Processing ID: 2RO2_A
Processing ID: 3CW1_v
Processing ID: 3HAY_E
Processing ID: 2K66_A
Processing ID: 2K5Z_A
Processing ID: 3A3A_A
Processing ID: 2KMJ_A
Processing ID: 2RPT_A
Processing ID: 3A2K_C
Processing ID: 2KOC_A
Processing ID: 2KD8_A
Processing ID: 2KE6_A
Processing ID: 2KHY_A
Processing ID: 2X7N_A
Processing ID: 2KUV_A
Processing ID: 2KUW_A
Processing ID: 2KUU_A
Processing ID: 2KUR_A
Processing ID: 2KPD_A
Processing ID: 2KPC_A
Processing ID: 2KVN_A
Processing ID: 3LWQ_D
Processing ID: 2KPV_A
Processing ID: 3JQ4_B
Processing ID: 3AKZ_H
Processing ID: 3IYR_A
Processing ID: 3IZ4_A
Processing ID: 2L3C_B
Processing ID: 2L1F_A
Processing ID: 2L2J_A
Processing ID: 2L1F_B
Processing ID: 2L3J_B
Processing ID: 2L3E_A
Processing ID: 3IZD_A
Processing ID: 2KRP_A
Processing ID: 3PGW_N
Processing ID: 2KRL_A
Processing ID: 2L5Z_A
Processing ID: 3NDB_M
Processing ID: 2KZL_A
Processing ID: 3PIP_Y
Processing ID: 2XXA_F
Processing ID: 2L6I_A
Processing ID: 3IZZ_E
Processing ID: 2LA5_A
Processing ID: 2LAC_A
Processing ID: 2LBS_A
Processing ID: 2LDT_A
Processing ID: 3AMU_B
Processing ID: 2Y95_A
Processing ID: 3TUP_T
Processing ID: 2LC8_A
Processing ID: 2LDL_A
Processing ID: 2LKR_A
Processing ID: 2LK3_A
Processing ID: 2LBJ_A
Processing ID: 2LBK_A
Processing ID: 2LBL_A
Processing ID: 2LPA_A
Processing ID: 2LP9_A
Processing ID: 4A4T_A
Processing ID: 4A4U_A
Processing ID: 4A4S_A
Processing ID: 3UZS_C
Processing ID: 2LHP_A
Processing ID: 2LUB_A
Processing ID: 2LQZ_A
Processing ID: 2LI4_A
Processing ID: 2LJJ_A
Processing ID: 4DR5_W
Processing ID: 4ILM_M
Processing ID: 2M21_A
Processing ID: 4ILL_C
Processing ID: 2M22_A
Processing ID: 2LU0_A
Processing ID: 3W1K_F
Processing ID: 3J3W_A
Processing ID: 3J3V_A
Processing ID: 3J3V_B
Processing ID: 2M8K_A
Processing ID: 2LV0_A
Processing ID: 4KJI_D
Processing ID: 4BY9_A
Processing ID: 2M12_A
Processing ID: 4C4Q_N
Processing ID: 2M23_A
Processing ID: 3WC2_Q
Processing ID: 2LUN_A
Processing ID: 3WC2_P
Processing ID: 3WC1_Q
Processing ID: 2MHI_A
Processing ID: 3WFR_D
Processing ID: 3WFQ_C
Processing ID: 2MEQ_A
Processing ID: 3WFR_B
Processing ID: 2MI0_B
Processing ID: 2MI0_A
Processing ID: 2MFG_D
Processing ID: 2MFC_B
Processing ID: 2M57_A
Processing ID: 2MFE_D
Processing ID: 2MFF_B
Processing ID: 2M4W_A
Processing ID: 2M5U_A
Processing ID: 3J6B_e
Processing ID: 4KR6_D
Processing ID: 2MF0_G
Processing ID: 4P8Z_A
Processing ID: 3WQZ_C
Processing ID: 4V6X_BC
Processing ID: 4V99_FX
Processing ID: 4V4N_A3
Processing ID: 4V6W_A7
Processing ID: 4V4N_B2
Processing ID: 4V5Z_BP
Processing ID: 4V4V_B0
Processing ID: 4V4W_B9
Processing ID: 4V8J_CW
Processing ID: 4V4V_AA
Processing ID: 4V6X_B2
Processing ID: 4V6W_A8
Processing ID: 4V4G_CA
Processing ID: 4V6U_A0
Processing ID: 4V6W_B2
Processing ID: 4V9B_CD
Processing ID: 4V4N_B1
Processing ID: 4V5G_BA
Processing ID: 4V7E_Ac
Processing ID: 4V65_A1
Processing ID: 4V6W_BC
Processing ID: 4V6X_A5
Processing ID: 4V5Z_BA
Processing ID: 4V5G_BB
Processing ID: 4V5Z_BH
Processing ID: 4V6D_AV
Processing ID: 4V7E_Ab
Processing ID: 4V5Z_BL
Processing ID: 4V6X_A7
Processing ID: 4V65_BB
Processing ID: 4V6X_A8
Processing ID: 4V5Z_BC
Processing ID: 4V8J_AV
Processing ID: 4V7E_Ad
Processing ID: 4V6U_B1
Processing ID: 4V7E_Aa
Processing ID: 4V5Z_BK
Processing ID: 4V5Z_AH
Processing ID: 4V4N_A1
Processing ID: 4V6W_A5
Processing ID: 4V5Z_BU
Processing ID: 4V7E_Ae
Processing ID: 4V5F_CA
Processing ID: 4V5Z_BQ
Processing ID: 4V5Z_AF
Processing ID: 4V5Z_BM
Processing ID: 4QIL_C
Processing ID: 4OQ9_3
Processing ID: 4TZV_B
Processing ID: 4TZP_C
Processing ID: 2MS1_B
Processing ID: 2MQT_A
Processing ID: 2MNC_A
Processing ID: 2MFD_A
Processing ID: 2MTJ_A
Processing ID: 4WSA_V
Processing ID: 3J8G_B
Processing ID: 3J8G_A
Processing ID: 4WJ3_Q
Processing ID: 4WZJ_VV
Processing ID: 4D5N_X
Processing ID: 4X4P_B
Processing ID: 4X4S_B
Processing ID: 4X0B_B
Processing ID: 4X0A_B
Processing ID: 4WC3_B
Processing ID: 5A18_A
Processing ID: 2MXJ_A
Processing ID: 2MXL_A
Processing ID: 4TUC_QY
Processing ID: 4TUA_XY
Processing ID: 2N0R_A
Processing ID: 2N1Q_A
Processing ID: 5AMQ_C
Processing ID: 4ZT9_D
Processing ID: 2N3Q_A
Processing ID: 4YVI_C
Processing ID: 4YVJ_C
Processing ID: 4YVK_C
Processing ID: 2N2P_A
Processing ID: 2N2O_A
Processing ID: 3JB9_C
Processing ID: 2N8V_X
Processing ID: 2N4L_A
Processing ID: 2N7M_X
Processing ID: 5ELS_I
Processing ID: 5FMZ_V
Processing ID: 5EPI_H
Processing ID: 5GAP_U
Processing ID: 5GAP_V
Processing ID: 2N7X_A
Processing ID: 4Z7L_F
Processing ID: 5FJ1_H
Processing ID: 3JD5_A
Processing ID: 2N6X_A
Processing ID: 2N6T_A
Processing ID: 2N6W_A
Processing ID: 2N6S_A
Processing ID: 2N3O_B
Processing ID: 2NBY_A
Processing ID: 2NC1_A
Processing ID: 2NC0_A
Processing ID: 5KK5_B
Processing ID: 2NBZ_A
Processing ID: 2NBX_A
Processing ID: 5KQE_A
Processing ID: 2NCI_A
Processing ID: 5KMZ_A
Processing ID: 5IEM_A
Processing ID: 5MC6_BR
Processing ID: 5MC6_BS
Processing ID: 5MC6_m
Processing ID: 5MC6_n
Processing ID: 2RVO_A
Processing ID: 5MS0_R
Processing ID: 5UZT_A
Processing ID: 5UF3_A
Processing ID: 5XBL_B
Processing ID: 5WQ1_A
Processing ID: 5V16_A
Processing ID: 5V17_A
Processing ID: 5KH8_A
Processing ID: 5OA3_1
Processing ID: 5O7H_A
Processing ID: 5LSN_A
Processing ID: 5V93_B
Processing ID: 5V93_a
Processing ID: 5V6X_C
Processing ID: 5V6X_D
Processing ID: 6AWD_A
Processing ID: 6AWC_A
Processing ID: 5XJ2_G
Processing ID: 5Y36_B
Processing ID: 6EVJ_V
Processing ID: 6C4H_x
Processing ID: 5N5C_A
Processing ID: 6FLQ_R
Processing ID: 6FT6_2
Processing ID: 5Z3G_B
Processing ID: 5ZAL_C
Processing ID: 5ZAM_C
Processing ID: 6C66_J
Processing ID: 5ZEY_B
Processing ID: 6DU5_B
Processing ID: 6AH3_T
Processing ID: 6AGB_A
Processing ID: 6MCE_A
Processing ID: 6BZ7_QW
Processing ID: 6BZ8_XY
Processing ID: 6BZ7_XY
Processing ID: 6AHU_A
Processing ID: 6AHU_T
Processing ID: 6CYT_N
Processing ID: 6MJ0_B
Processing ID: 6IFO_D
Processing ID: 6FHI_V
Processing ID: 6GBM_A
Processing ID: 6NDK_XY
Processing ID: 6AEB_E
Processing ID: 6IV6_G
Processing ID: 6QX9_1
Processing ID: 6QW6_5
Processing ID: 6HYK_A
Processing ID: 6DTI_X
Processing ID: 6AAX_D
Processing ID: 6NM9_G
Processing ID: 6K0B_U
Processing ID: 6K0A_X
Processing ID: 6O0Z_B
Processing ID: 6O0Y_B
Processing ID: 6S0X_B
Processing ID: 6S0Z_B
Processing ID: 6S0X_a
Processing ID: 6HYU_D
Processing ID: 6QWL_W
Processing ID: 6RR7_D
Processing ID: 6QX3_D
Processing ID: 6N7R_R
Processing ID: 6K4S_A
Processing ID: 6K3Z_A
Processing ID: 6KUT_V
Processing ID: 6KUV_V
Processing ID: 6POM_B
Processing ID: 6UFM_A
Processing ID: 6RFL_U
Processing ID: 6UES_A
Processing ID: 6SDW_B
Processing ID: 6SY6_D
Processing ID: 6V5B_D
Processing ID: 6MXQ_A
Processing ID: 6WPI_C
Processing ID: 6XWW_A
Processing ID: 6XWJ_A
Processing ID: 6ORD_QY
Processing ID: 6WB1_C
Processing ID: 6OJ2_QW
Processing ID: 6WB0_C
Processing ID: 6OF6_XW
Processing ID: 6OPE_XY
Processing ID: 6OJ2_QY
Processing ID: 6PK9_A
Processing ID: 6WLO_A
Processing ID: 6WLT_A
Processing ID: 6WD2_1
Processing ID: 6WD9_2
Processing ID: 6WLN_A
Processing ID: 6WLS_A
Processing ID: 6WLM_A
Processing ID: 6WLK_A
Processing ID: 6NOA_A
Processing ID: 6Z6B_UUU
Processing ID: 6XRZ_A
Processing ID: 6U79_A
Processing ID: 6VZC_A
Processing ID: 6W62_B
Processing ID: 6W64_B
Processing ID: 6W5C_B
Processing ID: 6W3M_A
Processing ID: 6O3M_XV
Processing ID: 6OSI_RB
Processing ID: 7D1A_A
Processing ID: 6LTP_H
Processing ID: 6XZR_IN1
Processing ID: 6Y0C_IN1
Processing ID: 6XZD_IN1
Processing ID: 6ZVK_d2
Processing ID: 6ZVK_h2
Processing ID: 6ZVK_K3
Processing ID: 6ZVK_E1
Processing ID: 6ZVK_e2
Processing ID: 7A01_e2
Processing ID: 7A01_K3
Processing ID: 6VAR_A
Processing ID: 7B9V_5
Processing ID: 7B9V_2
Processing ID: 7LVA_A
Processing ID: 7LJY_B
Processing ID: 6ZDU_C
Processing ID: 7LMA_B
Processing ID: 7LYG_A
Processing ID: 7LMB_B
Processing ID: 7D8C_B
Processing ID: 7DD4_A
Processing ID: 7OBQ_1
Processing ID: 7M5O_B
Processing ID: 7LYT_B
Processing ID: 7LYS_B
Processing ID: 7NQ4_C
Processing ID: 7ELE_G
Processing ID: 7JRT_B
Processing ID: 7JRS_B
Processing ID: 7K4L_A
Processing ID: 7DLZ_Y
Processing ID: 6WW6_E
Processing ID: 6WW6_F
Processing ID: 6WW6_C
Processing ID: 7NK4_D
Processing ID: 7SAM_A
Processing ID: 7M57_cc
Processing ID: 7M57_ii
Processing ID: 7M2T_ss
Processing ID: 7RQ5_A
Processing ID: 7LHD_A
Processing ID: 7RYG_B
Processing ID: 7ORJ_H
Processing ID: 7ORM_H
Processing ID: 7ORI_H
Processing ID: 7EXY_A
Processing ID: 7S4V_B
Processing ID: 7S4U_B
Processing ID: 7WB1_D
Processing ID: 7SLP_R
Processing ID: 7UGA_A
Processing ID: 7S36_R
Processing ID: 7S38_R
Processing ID: 7S3H_R
Processing ID: 7KUB_A
Processing ID: 7KUD_A
Processing ID: 7KUC_A
Processing ID: 7X34_3
Processing ID: 7V06_A
Processing ID: 7UMC_A
Processing ID: 7UMD_A
Processing ID: 7UME_A
Processing ID: 7XSN_N
Processing ID: 7URM_v
Processing ID: 7UR5_y
Processing ID: 7V59_C
Processing ID: 7UVT_A
Processing ID: 7VTN_B
Processing ID: 7U2A_C
Processing ID: 7UO0_C
Processing ID: 7UO1_C
Processing ID: 7PTL_B
Processing ID: 7PTQ_C
Processing ID: 7PTS_A
Processing ID: 7OZS_3
Processing ID: 7SHX_A
Processing ID: 7QGG_v
Processing ID: 7RGU_H
Processing ID: 8AW3_1
Processing ID: 8DVS_B
Processing ID: 8DK7_C
Processing ID: 8CTI_C
Processing ID: 7QDU_Q
Processing ID: 8DC2_B
Processing ID: 8BTZ_A
Processing ID: 8BD5_B
Processing ID: 8D4A_B
Processing ID: 8D49_B
Processing ID: 8EXY_R
Processing ID: 7YOJ_B
Processing ID: 7ZPQ_6
Processing ID: 8FCS_A
Processing ID: 7ZRS_6
Processing ID: 8E29_B
Processing ID: 7XW2_C
Processing ID: 7VW3_B
Processing ID: 8E79_R
Processing ID: 7ZAP_B
Processing ID: 8C98_A
Processing ID: 8C8X_B
Processing ID: 8C9C_A
Processing ID: 7YR7_A
Processing ID: 8G1I_B
Processing ID: 7ZRZ_ZN1
Processing ID: 8FZT_B
Processing ID: 8G1S_R
Processing ID: 8H69_5
Processing ID: 8GAP_B
Processing ID: 8SCF_A
Processing ID: 8SCH_A
Processing ID: 8CI5_C
Processing ID: 8CLR_A
Processing ID: 8SA6_A
Processing ID: 8IDF_B
Processing ID: 8EWG_B
Processing ID: 8BWT_A
Processing ID: 8EVQ_EC
Processing ID: 8EVR_EC
Processing ID: 8CQ1_A
Processing ID: 8U3M_A
Processing ID: 8UYL_A
Processing ID: 8UYS_A
Processing ID: 8UYJ_A
Processing ID: 8UYP_A
Processing ID: 8OMR_C
Processing ID: 8HUD_B
Processing ID: 8T2B_R
Processing ID: 8UPT_A
Processing ID: 8T2O_R
Processing ID: 8T29_R
Processing ID: 8T2A_R
Processing ID: 8VCI_A
Processing ID: 8BU8_A
Processing ID: 8T2P_B
Processing ID: 8T2P_A
Processing ID: 8PM4_B
Processing ID: 8IEW_B
Processing ID: 8TOC_R
Processing ID: 8J72_C
Processing ID: 8QO3_A
Processing ID: 8QO4_A
Processing ID: 8QO5_A
Processing ID: 8QO2_A
Processing ID: 8TVZ_C
Processing ID: 8H6E_4A
Processing ID: 8H6E_5A
Processing ID: 8P0B_V
Processing ID: 8P0G_V
Processing ID: 8JHP_A
Processing ID: 8Z85_D
Processing ID: 8Z90_D
Processing ID: 8Z8N_D
Processing ID: 8KAI_I
Processing ID: 8KAM_A
Processing ID: 8K8B_A
Processing ID: 8JTJ_B
Processing ID: 8WUS_B
Processing ID: 8YGJ_B
Processing ID: 8UO6_B
Processing ID: 8JTR_B
Processing ID: 8KAG_A
Processing ID: 8URY_d
Processing ID: 8URY_A
Processing ID: 9EOW_A
Processing ID: 8WT6_E
Processing ID: 8WT8_F
Processing ID: 8WT8_E
Processing ID: 8WT6_F
Processing ID: 8WT7_E
Processing ID: 8WT7_F
Processing ID: 8SFO_B
Processing ID: 8SFI_B
Processing ID: 8SFL_B
Processing ID: 8SFN_B
Processing ID: 8SFH_B
Processing ID: 8SFJ_B
Processing ID: 9ENF_C
Processing ID: 9ENE_D
Processing ID: 9ENC_D
Processing ID: 8OKD_X
Processing ID: 8OST_C
Processing ID: 8OPT_D
Processing ID: 8OPP_D
Processing ID: 8OPS_C
Processing ID: 8I0P_F
Processing ID: 8KDA_O
Processing ID: 8UAU_R
Processing ID: 9CF1_W
Processing ID: 9CF3_W
Processing ID: 8YE6_C
Processing ID: 8KI7_E
Processing ID: 9G8O_S2
Processing ID: 8UBE_I
Processing ID: 9DTT_B
Processing ID: 9G7C_A
Processing ID: 9FO8_A
Processing ID: 9FO9_A
Processing ID: 8XPP_B
Processing ID: 8T2Y_tA
Processing ID: 8T2Y_tP
Processing ID: 8XCA_B
Processing ID: 8T3E_EC
Processing ID: 8T3F_EC
Processing ID: 8XCC_B
Processing ID: 8Z1G_T
Processing ID: 8Z1F_T

     count  min_distance  max_distance  avg_distance
G-G   2171      3.171940     10.222204      7.634789
C-G      1      9.928677      9.928677      9.928677
C-U      1      6.809999      6.809999      6.809999
C-C   1577      3.685041      8.998447      7.307775
G-U      3      5.244127      8.603056      6.363770
A-U      2      8.795210      8.872931      8.834070
A-A    628      3.428841      8.995806      7.589609
A-C      1      9.739456      9.739456      9.739456
A-G      1      8.184795      8.184795      8.184795
U-U     64      4.861167      8.927059      7.549633